"""
EuroPath Immigration Explorer — Excel Workbook Builder
Generates a comprehensive 12-sheet workbook with dashboard, live country
search, comparisons, full pathway detail, charts, and conditional formatting.

Usage:
    pip install openpyxl
    python build_workbook.py

Input:  countries.json (45 countries, generated by scripts/export-countries.js)
Output: EuroPath_Immigration_Explorer.xlsx
"""
import json
import os
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.formatting.rule import ColorScaleRule, FormulaRule
from openpyxl.chart import BarChart, Reference
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation

HERE = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(HERE, "countries.json")) as f:
    COUNTRIES = json.load(f)

# ─── COLOR PALETTE ──────────────────────────────────────────
NAVY, DARK = "0F1A2E", "131F35"
PRIMARY, GREEN, BLUE = "6366F1", "22C55E", "0EA5E9"
AMBER, RED, PURPLE = "F59E0B", "EF4444", "A855F7"
WHITE, LIGHTGRAY, MIDGRAY, DARKTEXT = "FFFFFF", "F1F5F9", "94A3B8", "1E293B"
FONT_NAME = "Calibri"

def header_font(size=11, color=WHITE): return Font(name=FONT_NAME, bold=True, size=size, color=color)
def title_font(size=18, color=DARKTEXT): return Font(name=FONT_NAME, bold=True, size=size, color=color)
def body_font(size=10, color=DARKTEXT, bold=False, italic=False):
    return Font(name=FONT_NAME, size=size, color=color, bold=bold, italic=italic)
def fill(color): return PatternFill("solid", fgColor=color)

THIN = Side(style="thin", color="CBD5E1")
BORDER_ALL = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

def style_header_row(ws, row, n_cols, color=PRIMARY, start_col=1, size=10):
    for c in range(start_col, start_col + n_cols):
        cell = ws.cell(row=row, column=c)
        cell.font = header_font(size=size)
        cell.fill = fill(color)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = BORDER_ALL

def autosize(ws, widths):
    for col, w in widths.items():
        ws.column_dimensions[col].width = w

def freeze(ws, cell="A2"):
    ws.freeze_panes = cell

PATHWAY_TYPE_LABELS = {
    "residence":"Residence","skilled":"Skilled Worker","business":"Business/Entrepreneur",
    "investment":"Investment","family":"Family","heritage":"Descent/Heritage","eu":"EU/EEA Rights",
    "humanitarian":"Humanitarian","birthright":"Birthright","special":"Special/Discretionary",
    "adoption":"Adoption","treaty":"Treaty/Agreement","integration":"Exceptional Integration",
    "passive":"Passive Income","digital":"Digital Nomad","wealth":"Wealth-Based",
    "regularization":"Regularization","research":"Research/Academic"
}

wb = Workbook()
wb.remove(wb.active)
print(f"Loaded {len(COUNTRIES)} countries. Building workbook...")

# ═══════════════════════════════════════════════════════════
# SHEET 1: DASHBOARD
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("Dashboard")
ws.sheet_view.showGridLines = False
ws.merge_cells("A1:N1")
ws["A1"] = "🌍 EuroPath — Europe PR & Citizenship Explorer"
ws["A1"].font = title_font(size=22, color=WHITE)
ws["A1"].fill = fill(NAVY)
ws["A1"].alignment = Alignment(horizontal="center", vertical="center")
ws.row_dimensions[1].height = 40

ws.merge_cells("A2:N2")
ws["A2"] = f"Comprehensive Immigration Data for {len(COUNTRIES)} European Countries · Updated June 2025"
ws["A2"].font = body_font(size=11, color=MIDGRAY, italic=True)
ws["A2"].fill = fill(NAVY)
ws["A2"].alignment = Alignment(horizontal="center")
ws.row_dimensions[2].height = 22

stats = [
    ("Total Countries", len(COUNTRIES), PRIMARY),
    ("EU Members", sum(1 for c in COUNTRIES if c["eu"]), BLUE),
    ("Schengen Area", sum(1 for c in COUNTRIES if c["schengen"]), GREEN),
    ("Allow Dual Citizenship", sum(1 for c in COUNTRIES if c["dualCitizenship"]), AMBER),
    ("Digital Nomad Visas", sum(1 for c in COUNTRIES if c["digitalNomad"]), PURPLE),
    ("Fastest PR (yrs)", min(c["prYears"] for c in COUNTRIES if c["prYears"] < 999), RED),
]
row, col = 4, 1
for label, value, color in stats:
    ws.merge_cells(start_row=row, start_column=col, end_row=row, end_column=col+1)
    ws.merge_cells(start_row=row+1, start_column=col, end_row=row+1, end_column=col+1)
    c1 = ws.cell(row=row, column=col, value=label)
    c1.font = body_font(size=9, color=MIDGRAY); c1.alignment = Alignment(horizontal="center"); c1.fill = fill(LIGHTGRAY)
    c2 = ws.cell(row=row+1, column=col, value=value)
    c2.font = title_font(size=20, color=color); c2.alignment = Alignment(horizontal="center"); c2.fill = fill(LIGHTGRAY)
    col += 2
ws.row_dimensions[4].height = 18
ws.row_dimensions[5].height = 32

ws["A8"] = "📑 Navigate Workbook"
ws["A8"].font = title_font(size=13, color=DARKTEXT)
nav_sheets = [
    ("Country Search", "🔍 Type or pick any country for an instant full profile lookup"),
    ("Country Summary", "Full data for all countries, sortable/filterable"),
    ("PR Comparison", "Permanent residency timelines & requirements side-by-side"),
    ("Citizenship Comparison", "Citizenship timelines, dual-citizenship rules"),
    ("All PR Pathways", "Every permanent residency route, line by line"),
    ("All Citizenship Pathways", "Every citizenship route — ancestry, investment, family & more"),
    ("Visa Types", "Visa categories available per country"),
    ("Cost & Salary", "Cost of living and average salary comparison"),
    ("Quality of Life", "Healthcare, safety, education, startup scores"),
    ("Timeline Tracker", "Year-by-year immigration milestone tracker"),
    ("Glossary", "Definitions of immigration terms used throughout"),
]
r = 9
for sheet_name, desc in nav_sheets:
    cell = ws.cell(row=r, column=1, value=f"→ {sheet_name}")
    cell.font = Font(name=FONT_NAME, bold=True, size=11, color=PRIMARY, underline="single")
    cell.hyperlink = f"#'{sheet_name}'!A1"
    ws.cell(row=r, column=3, value=desc).font = body_font(size=10, color=MIDGRAY)
    r += 1

ws.merge_cells(f"A{r+1}:N{r+1}")
disclaimer = ws.cell(row=r+1, column=1,
    value="⚠ DISCLAIMER: Immigration laws change frequently. This workbook is for informational purposes only. "
          "Always verify current requirements with official government sources and consult a qualified immigration "
          "lawyer before making any decisions. Data compiled June 2025.")
disclaimer.font = body_font(size=9, color=AMBER, italic=True)
disclaimer.alignment = Alignment(wrap_text=True, vertical="top")
ws.row_dimensions[r+1].height = 30
autosize(ws, {"A":24,"B":24,"C":50,"D":14,"E":14,"F":14,"G":14,"H":14,"I":14,"J":14,"K":14,"L":14,"M":14,"N":14})

# ═══════════════════════════════════════════════════════════
# SHEET 1B: COUNTRY SEARCH (live lookup box)
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("Country Search")
ws.sheet_view.showGridLines = False
ws.merge_cells("A1:F1")
ws["A1"] = "🔍 Country Search"
ws["A1"].font = title_font(size=18, color=WHITE)
ws["A1"].fill = fill(NAVY)
ws["A1"].alignment = Alignment(horizontal="center", vertical="center")
ws.row_dimensions[1].height = 36

ws.merge_cells("A2:F2")
ws["A2"] = "Type or select a country below to instantly pull its full profile"
ws["A2"].font = body_font(size=10, color=MIDGRAY, italic=True)
ws["A2"].fill = fill(NAVY)
ws["A2"].alignment = Alignment(horizontal="center")
ws.row_dimensions[2].height = 20

ws.merge_cells("A4:B4")
ws["A4"] = "Search / Select Country:"
ws["A4"].font = body_font(bold=True, size=11)
ws["A4"].alignment = Alignment(horizontal="right", vertical="center")
ws.merge_cells("C4:E4")
search_cell = ws["C4"]
search_cell.value = "Germany"
search_cell.fill = fill("FEF9C3")
search_cell.font = Font(name=FONT_NAME, bold=True, size=13, color=DARKTEXT)
search_cell.alignment = Alignment(horizontal="center", vertical="center")
search_cell.border = Border(left=THIN, right=THIN, top=Side(style="medium", color=AMBER), bottom=Side(style="medium", color=AMBER))
ws.row_dimensions[4].height = 26

country_names = [c["name"] for c in COUNTRIES]
dv_search = DataValidation(type="list", formula1='"' + ",".join(country_names) + '"', allow_blank=False, showDropDown=False)
dv_search.error = "Please choose a country from the dropdown list."
dv_search.errorTitle = "Invalid country"
dv_search.prompt = "Start typing a country name or click the dropdown arrow"
dv_search.promptTitle = "Country Search"
ws.add_data_validation(dv_search)
dv_search.add(search_cell)

ws["F4"] = "💡 Click the cell, then use the dropdown arrow — or type the first letters of any country."
ws["F4"].font = body_font(size=8, italic=True, color=MIDGRAY)

ws.merge_cells("A5:F5")
flag_display = ws["A5"]
flag_display.value = "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,1,FALSE)&\"  \"&$C$4"
flag_display.font = Font(name=FONT_NAME, bold=True, size=24, color=DARKTEXT)
flag_display.alignment = Alignment(horizontal="center", vertical="center")
ws.row_dimensions[5].height = 36

result_rows = [
    ("Country Name", "=$C$4"),
    ("Capital", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,2,FALSE)"),
    ("Population", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,3,FALSE)"),
    ("Currency", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,4,FALSE)"),
    ("Languages", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,5,FALSE)"),
    ("EU Member", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,6,FALSE)"),
    ("Schengen", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,7,FALSE)"),
    ("PR Eligibility (years)", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,8,FALSE)"),
    ("Citizenship (years)", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,9,FALSE)"),
    ("Dual Citizenship Allowed", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,10,FALSE)"),
    ("Average Salary", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,11,FALSE)"),
    ("Cost of Living", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,12,FALSE)"),
    ("Tax Rate", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,13,FALSE)"),
    ("Healthcare Score (/10)", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,14,FALSE)"),
    ("Safety Score (/10)", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,15,FALSE)"),
    ("Education Score (/10)", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,16,FALSE)"),
    ("Digital Nomad Visa", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,17,FALSE)"),
    ("Passport Rank (Henley)", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,18,FALSE)"),
    ("Number of PR Pathways", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,19,FALSE)"),
    ("Number of Citizenship Pathways", "=VLOOKUP($C$4,'Country Summary'!$B$2:$U$46,20,FALSE)"),
]
r = 7
ws.cell(row=r, column=1, value="FIELD").font = header_font(size=10)
ws.cell(row=r, column=1).fill = fill(PRIMARY)
ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=4)
ws.cell(row=r, column=2, value="RESULT").font = header_font(size=10)
ws.cell(row=r, column=2).fill = fill(PRIMARY)
ws.cell(row=r, column=2).alignment = Alignment(horizontal="center")
for cc in range(1,5): ws.cell(row=r, column=cc).border = BORDER_ALL
r += 1
for label, formula in result_rows:
    ws.cell(row=r, column=1, value=label).font = body_font(bold=True, size=10)
    ws.cell(row=r, column=1).fill = fill(LIGHTGRAY)
    ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=4)
    rc = ws.cell(row=r, column=2, value=formula)
    rc.font = body_font(size=11, color=DARKTEXT)
    rc.alignment = Alignment(horizontal="center", vertical="center")
    for cc in range(1,5): ws.cell(row=r, column=cc).border = BORDER_ALL
    ws.row_dimensions[r].height = 20
    r += 1

ws.merge_cells(start_row=r+1, start_column=1, end_row=r+1, end_column=5)
hint = ws.cell(row=r+1, column=1,
    value="For full pathway-by-pathway detail, go to 'All PR Pathways' or 'All Citizenship Pathways' "
          "and use Excel's column filter (▼) on the Country column.")
hint.font = body_font(size=9, italic=True, color=MIDGRAY)
hint.alignment = Alignment(wrap_text=True)
ws.row_dimensions[r+1].height = 30
autosize(ws, {"A":26,"B":18,"C":18,"D":18,"E":18,"F":40})

# ═══════════════════════════════════════════════════════════
# SHEET 2: COUNTRY SUMMARY
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("Country Summary")
ws.sheet_view.showGridLines = False
headers = ["Flag","Country","Capital","Population","Currency","Languages","EU Member","Schengen",
           "PR (yrs)","Citizenship (yrs)","Dual Citizenship","Avg Salary","Cost of Living",
           "Tax Rate","Healthcare","Safety","Education","Digital Nomad Visa","Passport Rank",
           "PR Pathways #","Citizenship Pathways #"]
ws.append(headers)
style_header_row(ws, 1, len(headers), color=PRIMARY)
ws.row_dimensions[1].height = 32

for i, c in enumerate(COUNTRIES, start=2):
    ws.cell(row=i, column=1, value=c["flag"])
    ws.cell(row=i, column=2, value=c["name"]).font = body_font(bold=True)
    ws.cell(row=i, column=3, value=c["capital"])
    ws.cell(row=i, column=4, value=c["population"])
    ws.cell(row=i, column=5, value=c["currency"])
    ws.cell(row=i, column=6, value=", ".join(c["languages"]))
    ws.cell(row=i, column=7, value="Yes" if c["eu"] else "No")
    ws.cell(row=i, column=8, value="Yes" if c["schengen"] else "No")
    ws.cell(row=i, column=9, value=c["prYears"] if c["prYears"] < 999 else "N/A")
    ws.cell(row=i, column=10, value=c["citizenshipYears"] if c["citizenshipYears"] < 999 else "N/A")
    ws.cell(row=i, column=11, value="Yes" if c["dualCitizenship"] else "No")
    ws.cell(row=i, column=12, value=c["avgSalary"])
    ws.cell(row=i, column=13, value=c["costOfLiving"])
    ws.cell(row=i, column=14, value=c["taxRate"])
    ws.cell(row=i, column=15, value=c["healthcare"])
    ws.cell(row=i, column=16, value=c["safety"])
    ws.cell(row=i, column=17, value=c["education"])
    ws.cell(row=i, column=18, value="Yes" if c["digitalNomad"] else "No")
    ws.cell(row=i, column=19, value=c["passportRank"])
    ws.cell(row=i, column=20, value=len(c.get("prPathways", [])))
    ws.cell(row=i, column=21, value=len(c.get("citizenshipPathways", [])))
    for col in range(1, len(headers)+1):
        ws.cell(row=i, column=col).border = BORDER_ALL
        if col not in (2,):
            ws.cell(row=i, column=col).alignment = Alignment(horizontal="center")

last_row = len(COUNTRIES) + 1
tbl = Table(displayName="CountrySummary", ref=f"A1:U{last_row}")
tbl.tableStyleInfo = TableStyleInfo(name="TableStyleMedium9", showRowStripes=True)
ws.add_table(tbl)
freeze(ws, "C2")
ws.conditional_formatting.add(f"I2:I{last_row}", ColorScaleRule(start_type="min", start_color="C6F6D5", end_type="max", end_color="FCA5A5"))
ws.conditional_formatting.add(f"J2:J{last_row}", ColorScaleRule(start_type="min", start_color="C6F6D5", end_type="max", end_color="FCA5A5"))
ws.conditional_formatting.add(f"O2:Q{last_row}", ColorScaleRule(start_type="min", start_color="FCA5A5", end_type="max", end_color="C6F6D5"))
autosize(ws, {"A":6,"B":18,"C":16,"D":12,"E":14,"F":18,"G":10,"H":10,"I":9,"J":13,"K":12,
              "L":13,"M":13,"N":12,"O":10,"P":8,"Q":10,"R":12,"S":11,"T":11,"U":14})

# ═══════════════════════════════════════════════════════════
# SHEET 3: PR COMPARISON
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("PR Comparison")
ws.sheet_view.showGridLines = False
headers = ["Flag","Country","Standard PR (yrs)","Fastest PR Route","Fastest PR (yrs)",
           "Number of PR Routes","Has Investment Route","Has Skilled Fast-Track",
           "Has Family Route","EU Long-Term Resident Option"]
ws.append(headers)
style_header_row(ws, 1, len(headers), color=GREEN)
ws.row_dimensions[1].height = 28

sorted_by_pr = sorted(COUNTRIES, key=lambda c: c["prYears"])
for i, c in enumerate(sorted_by_pr, start=2):
    pr_paths = c.get("prPathways", [])
    fastest = min(pr_paths, key=lambda p: p["years"]) if pr_paths else None
    ws.cell(row=i, column=1, value=c["flag"])
    ws.cell(row=i, column=2, value=c["name"]).font = body_font(bold=True)
    ws.cell(row=i, column=3, value=c["prYears"] if c["prYears"] < 999 else "N/A")
    ws.cell(row=i, column=4, value=fastest["name"] if fastest else "—")
    ws.cell(row=i, column=5, value=fastest["years"] if fastest else "—")
    ws.cell(row=i, column=6, value=len(pr_paths))
    ws.cell(row=i, column=7, value="Yes" if any(p["type"]=="investment" for p in pr_paths) else "No")
    ws.cell(row=i, column=8, value="Yes" if any(p["type"]=="skilled" for p in pr_paths) else "No")
    ws.cell(row=i, column=9, value="Yes" if any(p["type"]=="family" for p in pr_paths) else "No")
    ws.cell(row=i, column=10, value="Yes" if any(p["type"]=="eu" for p in pr_paths) else "No")
    for col in range(1, len(headers)+1):
        ws.cell(row=i, column=col).border = BORDER_ALL
        if col != 2 and col != 4:
            ws.cell(row=i, column=col).alignment = Alignment(horizontal="center")

last_row = len(COUNTRIES) + 1
tbl = Table(displayName="PRComparison", ref=f"A1:J{last_row}")
tbl.tableStyleInfo = TableStyleInfo(name="TableStyleMedium7", showRowStripes=True)
ws.add_table(tbl)
freeze(ws, "C2")
ws.conditional_formatting.add(f"C2:C{last_row}", ColorScaleRule(start_type="min", start_color="C6F6D5", end_type="max", end_color="FCA5A5"))
autosize(ws, {"A":6,"B":18,"C":15,"D":34,"E":13,"F":13,"G":15,"H":17,"I":14,"J":22})

# ═══════════════════════════════════════════════════════════
# SHEET 4: CITIZENSHIP COMPARISON
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("Citizenship Comparison")
ws.sheet_view.showGridLines = False
headers = ["Flag","Country","Standard Citizenship (yrs)","Dual Citizenship Allowed",
           "Fastest Route","Fastest (yrs)","Has Ancestry/Heritage Route","Has Investment Route",
           "Has Family Route","Number of Routes"]
ws.append(headers)
style_header_row(ws, 1, len(headers), color=PRIMARY)
ws.row_dimensions[1].height = 28

sorted_by_cit = sorted(COUNTRIES, key=lambda c: c["citizenshipYears"])
for i, c in enumerate(sorted_by_cit, start=2):
    cit_paths = c.get("citizenshipPathways", [])
    fastest = min(cit_paths, key=lambda p: p["years"]) if cit_paths else None
    ws.cell(row=i, column=1, value=c["flag"])
    ws.cell(row=i, column=2, value=c["name"]).font = body_font(bold=True)
    ws.cell(row=i, column=3, value=c["citizenshipYears"] if c["citizenshipYears"] < 999 else "N/A")
    ws.cell(row=i, column=4, value="Yes" if c["dualCitizenship"] else "No")
    ws.cell(row=i, column=5, value=fastest["name"] if fastest else "—")
    ws.cell(row=i, column=6, value=fastest["years"] if fastest else "—")
    ws.cell(row=i, column=7, value="Yes" if any(p["type"]=="heritage" for p in cit_paths) else "No")
    ws.cell(row=i, column=8, value="Yes" if any(p["type"]=="investment" for p in cit_paths) else "No")
    ws.cell(row=i, column=9, value="Yes" if any(p["type"]=="family" for p in cit_paths) else "No")
    ws.cell(row=i, column=10, value=len(cit_paths))
    for col in range(1, len(headers)+1):
        ws.cell(row=i, column=col).border = BORDER_ALL
        if col != 2 and col != 5:
            ws.cell(row=i, column=col).alignment = Alignment(horizontal="center")

last_row = len(COUNTRIES) + 1
tbl = Table(displayName="CitizenshipComparison", ref=f"A1:J{last_row}")
tbl.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True)
ws.add_table(tbl)
freeze(ws, "C2")
ws.conditional_formatting.add(f"C2:C{last_row}", ColorScaleRule(start_type="min", start_color="C6F6D5", end_type="max", end_color="FCA5A5"))
for col_letter in ["D","G","H","I"]:
    ws.conditional_formatting.add(f"{col_letter}2:{col_letter}{last_row}", FormulaRule(formula=[f'{col_letter}2="Yes"'], fill=fill("D1FAE5")))
autosize(ws, {"A":6,"B":18,"C":20,"D":18,"E":34,"F":11,"G":20,"H":17,"I":14,"J":13})

# ═══════════════════════════════════════════════════════════
# SHEET 5: ALL PR PATHWAYS
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("All PR Pathways")
ws.sheet_view.showGridLines = False
headers = ["Flag","Country","Pathway Name","Route Type","Years to PR","Requirements","Notes"]
ws.append(headers)
style_header_row(ws, 1, len(headers), color=GREEN, size=11)
ws.row_dimensions[1].height = 24

row = 2
for c in COUNTRIES:
    for p in c.get("prPathways", []):
        ws.cell(row=row, column=1, value=c["flag"])
        ws.cell(row=row, column=2, value=c["name"]).font = body_font(bold=True)
        ws.cell(row=row, column=3, value=p["name"])
        ws.cell(row=row, column=4, value=PATHWAY_TYPE_LABELS.get(p["type"], p["type"]))
        yrs = p["years"]
        ws.cell(row=row, column=5, value=("Instant" if yrs==0 else ("N/A" if yrs>=999 else yrs)))
        ws.cell(row=row, column=6, value=p["requirements"]).alignment = Alignment(wrap_text=True, vertical="top")
        ws.cell(row=row, column=7, value=p.get("notes","")).alignment = Alignment(wrap_text=True, vertical="top")
        for col in range(1, 8):
            ws.cell(row=row, column=col).border = BORDER_ALL
            if col in (1,4,5):
                ws.cell(row=row, column=col).alignment = Alignment(horizontal="center", vertical="top")
        ws.cell(row=row, column=2).alignment = Alignment(vertical="top")
        ws.cell(row=row, column=3).alignment = Alignment(vertical="top", wrap_text=True)
        ws.row_dimensions[row].height = 45
        row += 1

last_row = row - 1
tbl = Table(displayName="AllPRPathways", ref=f"A1:G{last_row}")
tbl.tableStyleInfo = TableStyleInfo(name="TableStyleMedium7", showRowStripes=True)
ws.add_table(tbl)
freeze(ws, "C2")
autosize(ws, {"A":6,"B":16,"C":32,"D":18,"E":11,"F":55,"G":48})

# ═══════════════════════════════════════════════════════════
# SHEET 6: ALL CITIZENSHIP PATHWAYS
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("All Citizenship Pathways")
ws.sheet_view.showGridLines = False
headers = ["Flag","Country","Pathway Name","Route Type","Years to Citizenship","Requirements","Notes"]
ws.append(headers)
style_header_row(ws, 1, len(headers), color=PRIMARY, size=11)
ws.row_dimensions[1].height = 24

row = 2
for c in COUNTRIES:
    for p in c.get("citizenshipPathways", []):
        ws.cell(row=row, column=1, value=c["flag"])
        ws.cell(row=row, column=2, value=c["name"]).font = body_font(bold=True)
        ws.cell(row=row, column=3, value=p["name"])
        ws.cell(row=row, column=4, value=PATHWAY_TYPE_LABELS.get(p["type"], p["type"]))
        yrs = p["years"]
        ws.cell(row=row, column=5, value=("Instant" if yrs==0 else ("N/A" if yrs>=999 else yrs)))
        ws.cell(row=row, column=6, value=p["requirements"]).alignment = Alignment(wrap_text=True, vertical="top")
        ws.cell(row=row, column=7, value=p.get("notes","")).alignment = Alignment(wrap_text=True, vertical="top")
        for col in range(1, 8):
            ws.cell(row=row, column=col).border = BORDER_ALL
            if col in (1,4,5):
                ws.cell(row=row, column=col).alignment = Alignment(horizontal="center", vertical="top")
        ws.cell(row=row, column=2).alignment = Alignment(vertical="top")
        ws.cell(row=row, column=3).alignment = Alignment(vertical="top", wrap_text=True)
        ws.row_dimensions[row].height = 45
        if p["type"] == "heritage":
            for col in range(1, 8):
                ws.cell(row=row, column=col).fill = fill("FEF3C7")
        row += 1

last_row = row - 1
tbl = Table(displayName="AllCitizenshipPathways", ref=f"A1:G{last_row}")
tbl.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True)
ws.add_table(tbl)
freeze(ws, "C2")
autosize(ws, {"A":6,"B":16,"C":34,"D":20,"E":15,"F":55,"G":48})

# ═══════════════════════════════════════════════════════════
# SHEET 7: VISA TYPES
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("Visa Types")
ws.sheet_view.showGridLines = False
headers = ["Flag","Country","Visa Category","Description"]
ws.append(headers)
style_header_row(ws, 1, len(headers), color=AMBER)
ws.row_dimensions[1].height = 22

VISA_DESC = {
    "Skilled Worker":"For professionals with job offers. Employer sponsorship typically required with salary threshold.",
    "EU Blue Card":"EU-wide highly-qualified worker permit. Minimum salary and degree requirements apply.",
    "Digital Nomad":"Work remotely for non-domestic employers while residing in-country. Income above threshold required.",
    "Student":"For enrolled students at recognised institutions. Limited work rights typically apply.",
    "Family Reunification":"For family members of legal residents. Sponsor must meet income and housing requirements.",
    "Golden Visa":"Investment-based residency through real estate or capital investment. Low/no physical presence required.",
    "Investor":"Business or capital investment residency pathway. Varies by investment amount and type.",
    "Entrepreneur":"For those establishing or running a business. Business plan and capital requirements apply.",
    "Startup":"For founders of innovative, high-growth startups. Endorsement by innovation body typically required.",
    "Research":"For academic researchers affiliated with recognised institutions. Hosting agreement required.",
    "Seasonal":"Temporary permits for agricultural, tourism, hospitality workers. Usually summer season only.",
    "Job Seeker":"Short-term permit to actively search for employment without prior job offer.",
}
row = 2
for c in COUNTRIES:
    for v in c["visas"]:
        ws.cell(row=row, column=1, value=c["flag"])
        ws.cell(row=row, column=2, value=c["name"]).font = body_font(bold=True)
        ws.cell(row=row, column=3, value=v)
        ws.cell(row=row, column=4, value=VISA_DESC.get(v, f"Legal pathway for {v.lower()} activities."))
        for col in range(1,5):
            ws.cell(row=row, column=col).border = BORDER_ALL
            if col in (1,):
                ws.cell(row=row, column=col).alignment = Alignment(horizontal="center")
        ws.cell(row=row, column=4).alignment = Alignment(wrap_text=True)
        row += 1
last_row = row - 1
tbl = Table(displayName="VisaTypes", ref=f"A1:D{last_row}")
tbl.tableStyleInfo = TableStyleInfo(name="TableStyleMedium4", showRowStripes=True)
ws.add_table(tbl)
freeze(ws, "C2")
autosize(ws, {"A":6,"B":18,"C":24,"D":70})

# ═══════════════════════════════════════════════════════════
# SHEET 8: COST & SALARY
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("Cost & Salary")
ws.sheet_view.showGridLines = False
headers = ["Flag","Country","Avg Salary (local)","Cost of Living","Tax Rate","Healthcare Score","Safety Score"]
ws.append(headers)
style_header_row(ws, 1, len(headers), color=BLUE)
ws.row_dimensions[1].height = 22

for i, c in enumerate(COUNTRIES, start=2):
    ws.cell(row=i, column=1, value=c["flag"])
    ws.cell(row=i, column=2, value=c["name"]).font = body_font(bold=True)
    ws.cell(row=i, column=3, value=c["avgSalary"])
    ws.cell(row=i, column=4, value=c["costOfLiving"])
    ws.cell(row=i, column=5, value=c["taxRate"])
    ws.cell(row=i, column=6, value=c["healthcare"])
    ws.cell(row=i, column=7, value=c["safety"])
    for col in range(1,8):
        ws.cell(row=i, column=col).border = BORDER_ALL
        if col not in (2,3,5):
            ws.cell(row=i, column=col).alignment = Alignment(horizontal="center")
last_row = len(COUNTRIES) + 1
tbl = Table(displayName="CostSalary", ref=f"A1:G{last_row}")
tbl.tableStyleInfo = TableStyleInfo(name="TableStyleMedium11", showRowStripes=True)
ws.add_table(tbl)
freeze(ws, "C2")
ws.conditional_formatting.add(f"F2:G{last_row}", ColorScaleRule(start_type="min", start_color="FCA5A5", end_type="max", end_color="C6F6D5"))
autosize(ws, {"A":6,"B":18,"C":18,"D":15,"E":16,"F":15,"G":13})

chart = BarChart()
chart.title = "Healthcare Score by Country (Top 15)"
chart.y_axis.title = "Score (out of 10)"
chart.style = 10
helper_start_row = last_row + 4
ws.cell(row=helper_start_row-1, column=1, value="Top 15 Countries by Healthcare Score").font = title_font(size=12)
ws.cell(row=helper_start_row, column=1, value="Country")
ws.cell(row=helper_start_row, column=2, value="Healthcare")
top_countries = sorted(COUNTRIES, key=lambda c: c["healthcare"], reverse=True)[:15]
for i, c in enumerate(top_countries):
    ws.cell(row=helper_start_row+1+i, column=1, value=c["name"])
    ws.cell(row=helper_start_row+1+i, column=2, value=c["healthcare"])
data = Reference(ws, min_col=2, min_row=helper_start_row, max_row=helper_start_row+15)
cats = Reference(ws, min_col=1, min_row=helper_start_row+1, max_row=helper_start_row+15)
chart.add_data(data, titles_from_data=True)
chart.set_categories(cats)
chart.width, chart.height = 22, 11
ws.add_chart(chart, f"I{helper_start_row-1}")

# ═══════════════════════════════════════════════════════════
# SHEET 9: QUALITY OF LIFE
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("Quality of Life")
ws.sheet_view.showGridLines = False
headers = ["Flag","Country","Healthcare","Safety","Education","Startup Score","Family Friendly","Retirement Friendly"]
ws.append(headers)
style_header_row(ws, 1, len(headers), color=PURPLE)
ws.row_dimensions[1].height = 22

for i, c in enumerate(COUNTRIES, start=2):
    ws.cell(row=i, column=1, value=c["flag"])
    ws.cell(row=i, column=2, value=c["name"]).font = body_font(bold=True)
    ws.cell(row=i, column=3, value=c["healthcare"])
    ws.cell(row=i, column=4, value=c["safety"])
    ws.cell(row=i, column=5, value=c["education"])
    ws.cell(row=i, column=6, value=c["startupScore"])
    ws.cell(row=i, column=7, value=c["familyFriendly"])
    ws.cell(row=i, column=8, value=c["retirementFriendly"])
    for col in range(1,9):
        ws.cell(row=i, column=col).border = BORDER_ALL
        if col != 2:
            ws.cell(row=i, column=col).alignment = Alignment(horizontal="center")
last_row = len(COUNTRIES) + 1
tbl = Table(displayName="QualityOfLife", ref=f"A1:H{last_row}")
tbl.tableStyleInfo = TableStyleInfo(name="TableStyleMedium8", showRowStripes=True)
ws.add_table(tbl)
freeze(ws, "C2")
for col_letter in ["C","D","E","F","G","H"]:
    ws.conditional_formatting.add(f"{col_letter}2:{col_letter}{last_row}", ColorScaleRule(start_type="min", start_color="FCA5A5", end_type="max", end_color="C6F6D5"))
autosize(ws, {"A":6,"B":18,"C":13,"D":11,"E":13,"F":15,"G":17,"H":18})

summary_row = last_row + 2
ws.cell(row=summary_row, column=2, value="AVERAGE (all countries)").font = body_font(bold=True, italic=True)
for col_letter, col_idx in zip(["C","D","E","F","G","H"], range(3,9)):
    ws.cell(row=summary_row, column=col_idx, value=f"=AVERAGE({col_letter}2:{col_letter}{last_row})")
    ws.cell(row=summary_row, column=col_idx).font = body_font(bold=True)
    ws.cell(row=summary_row, column=col_idx).number_format = "0.00"
    ws.cell(row=summary_row, column=col_idx).alignment = Alignment(horizontal="center")

# ═══════════════════════════════════════════════════════════
# SHEET 10: TIMELINE TRACKER
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("Timeline Tracker")
ws.sheet_view.showGridLines = False
ws.merge_cells("A1:H1")
ws["A1"] = "Immigration Timeline Tracker — Plan Your Journey"
ws["A1"].font = title_font(size=15)
ws["A1"].fill = fill(LIGHTGRAY)
ws.row_dimensions[1].height = 26

ws["A3"] = "Select a country:"
ws["A3"].font = body_font(bold=True)
ws["B3"] = "Germany"
ws["B3"].fill = fill("FEF9C3")
ws["B3"].font = body_font(bold=True, color=DARKTEXT)
ws["B3"].border = BORDER_ALL
dv = DataValidation(type="list", formula1='"' + ",".join(country_names) + '"', allow_blank=False)
ws.add_data_validation(dv)
dv.add(ws["B3"])

headers = ["Milestone","Year","Status (mark X when complete)","Notes"]
ws.append([])
ws.append(headers)
hdr_row = 5
style_header_row(ws, hdr_row, len(headers), color=PRIMARY)
milestones = ["Arrival & Registration","First Permit Renewal","Language Certification Obtained",
              "Permanent Residency Eligible","Citizenship Eligible","Passport Issued"]
for i, m in enumerate(milestones):
    r = hdr_row + 1 + i
    ws.cell(row=r, column=1, value=m)
    for col in range(2,5): ws.cell(row=r, column=col, value="")
    for col in range(1,5): ws.cell(row=r, column=col).border = BORDER_ALL
ws.cell(row=hdr_row+4, column=2, value="=VLOOKUP($B$3,'Country Summary'!$B$2:$J$46,8,FALSE)")
ws.cell(row=hdr_row+5, column=2, value="=VLOOKUP($B$3,'Country Summary'!$B$2:$J$46,9,FALSE)")

note = ws.cell(row=hdr_row+8, column=1,
    value="Tip: Change the country in cell B3 to auto-populate PR and Citizenship year estimates above. "
          "Mark milestones complete as you progress through your immigration journey.")
note.font = body_font(size=9, italic=True, color=MIDGRAY)
ws.merge_cells(start_row=hdr_row+8, start_column=1, end_row=hdr_row+8, end_column=4)
note.alignment = Alignment(wrap_text=True)
autosize(ws, {"A":30,"B":14,"C":30,"D":40})

# ═══════════════════════════════════════════════════════════
# SHEET 11: GLOSSARY
# ═══════════════════════════════════════════════════════════
ws = wb.create_sheet("Glossary")
ws.sheet_view.showGridLines = False
ws.merge_cells("A1:C1")
ws["A1"] = "Glossary of Immigration Terms"
ws["A1"].font = title_font(size=16)
ws["A1"].fill = fill(LIGHTGRAY)
ws.row_dimensions[1].height = 28

headers = ["Term","Definition","Also Known As"]
ws.append([])
ws.append(headers)
style_header_row(ws, 3, len(headers), color=DARKTEXT)

glossary = [
    ("Permanent Residency (PR)","Legal status granting indefinite right to live and usually work in a country, without full citizenship rights such as voting.","Settlement, Indefinite Leave to Remain (UK), Daueraufenthalt (Germany)"),
    ("Naturalization","The legal process by which a foreign national acquires citizenship, typically after meeting residency, language, and integration requirements.","Citizenship by application"),
    ("Jus Sanguinis","Latin for 'right of blood' — citizenship acquired through descent from a parent or grandparent who holds that citizenship, regardless of birthplace.","Citizenship by descent, Ancestry citizenship"),
    ("Jus Soli","Latin for 'right of soil' — citizenship acquired by being born within a country's territory.","Birthright citizenship"),
    ("Dual Citizenship","Holding the citizenship of two countries simultaneously, recognized as legal by both states.","Multiple citizenship, Dual nationality"),
    ("Golden Visa","A residency permit granted in exchange for a qualifying investment, typically real estate or government bonds.","Citizenship/Residency by Investment (CBI/RBI)"),
    ("EU Blue Card","A work and residence permit for highly qualified non-EU nationals, valid across most EU member states.",""),
    ("Schengen Area","A zone of European countries that have abolished passport and immigration controls at their mutual borders.","Schengen Zone"),
    ("Long-Term Resident Permit (EU)","An EU-wide status granted after 5 years of legal residence, offering enhanced mobility rights across the EU.","EC Long-Term Residence"),
    ("Civic Integration Test","An examination assessing knowledge of a country's language, history, culture, and legal system, often required for citizenship.","Naturalization test"),
    ("Family Reunification","A legal pathway allowing family members of a legal resident or citizen to join them.",""),
    ("Digital Nomad Visa","A residence permit allowing remote workers to legally live in a country while working for employers/clients based elsewhere.","Remote work visa"),
    ("Repatriation","A legal process allowing individuals of a country's ethnic or ancestral origin to acquire citizenship, sometimes without standard residency.",""),
    ("Statelessness","The condition of not being recognized as a citizen by any country.",""),
    ("Passport Rank (Henley Index)","A ranking of passports based on the number of countries their holders can enter without a prior visa.","Henley Passport Index"),
    ("Reckonable Residence","Legal term (notably in Ireland) for residence time counting toward naturalization eligibility.",""),
    ("Investor Visa","A residence permit granted based on a qualifying business or capital investment.",""),
    ("Working Holiday Visa","A temporary visa, usually for younger applicants, combining travel and short-term employment.",""),
    ("Sephardic Citizenship Laws","Special restitution laws granting citizenship to descendants of Sephardic Jews expelled in the 15th century.",""),
    ("Compatriot/Diaspora Status","Legal recognition granted to ethnic diaspora members, often easing immigration and citizenship.","Karta Polaka (Poland), Slovak Living Abroad"),
]
for i, (term, definition, aka) in enumerate(glossary, start=4):
    ws.cell(row=i, column=1, value=term).font = body_font(bold=True)
    ws.cell(row=i, column=2, value=definition).alignment = Alignment(wrap_text=True, vertical="top")
    ws.cell(row=i, column=3, value=aka).alignment = Alignment(wrap_text=True, vertical="top")
    for col in range(1,4): ws.cell(row=i, column=col).border = BORDER_ALL
    ws.row_dimensions[i].height = 48
autosize(ws, {"A":26,"B":80,"C":40})
freeze(ws, "A4")

# ═══════════════════════════════════════════════════════════
# SAVE
# ═══════════════════════════════════════════════════════════
wb.active = 0
out_path = os.path.join(HERE, "EuroPath_Immigration_Explorer.xlsx")
wb.save(out_path)
print(f"Saved workbook to {out_path}")
print(f"Sheets: {wb.sheetnames}")
